/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubjectResult = IDL.Record({
  'subjectName' : IDL.Text,
  'marksObtained' : IDL.Nat,
  'maxMarks' : IDL.Nat,
});
export const Time = IDL.Int;
export const Result = IDL.Record({
  'totalMarks' : IDL.Nat,
  'studentName' : IDL.Text,
  'subjects' : IDL.Vec(SubjectResult),
  'grade' : IDL.Text,
  'rollNumber' : IDL.Text,
  'timestamp' : Time,
  'obtainedMarks' : IDL.Nat,
  'examName' : IDL.Text,
  'percentage' : IDL.Float64,
  'passed' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserInfo = IDL.Record({
  'principal' : IDL.Principal,
  'email' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateResult' : IDL.Func([Result], [], []),
  'askGemini' : IDL.Func([IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteResult' : IDL.Func([IDL.Text], [], []),
  'getAllResults' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(Result)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyEmail' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getResultByRollNumber' : IDL.Func([IDL.Text], [IDL.Opt(Result)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubjectResult = IDL.Record({
    'subjectName' : IDL.Text,
    'marksObtained' : IDL.Nat,
    'maxMarks' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Result = IDL.Record({
    'totalMarks' : IDL.Nat,
    'studentName' : IDL.Text,
    'subjects' : IDL.Vec(SubjectResult),
    'grade' : IDL.Text,
    'rollNumber' : IDL.Text,
    'timestamp' : Time,
    'obtainedMarks' : IDL.Nat,
    'examName' : IDL.Text,
    'percentage' : IDL.Float64,
    'passed' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserInfo = IDL.Record({
    'principal' : IDL.Principal,
    'email' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateResult' : IDL.Func([Result], [], []),
    'askGemini' : IDL.Func([IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteResult' : IDL.Func([IDL.Text], [], []),
    'getAllResults' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Result)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyEmail' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getResultByRollNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Result)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };